import type {
  AppNotification,
  Earning,
  Job,
  Part,
  ProUser,
  Rating,
  TimelineStep,
} from '@/types/dribee';

const baseTimeline = (current: number): TimelineStep[] => {
  const steps = [
    { key: 'assigned', label: 'Assigned', timestamp: '20 Apr, 09:14 AM' },
    { key: 'accepted', label: 'Accepted', timestamp: '20 Apr, 09:18 AM' },
    { key: 'otp', label: 'OTP Verified', timestamp: '20 Apr, 10:02 AM' },
    { key: 'inProgress', label: 'In Progress', timestamp: '20 Apr, 10:05 AM' },
    { key: 'partsSent', label: 'Parts Sent', timestamp: '20 Apr, 10:34 AM' },
    { key: 'partsApproved', label: 'Parts Approved', timestamp: '20 Apr, 11:12 AM' },
    { key: 'completed', label: 'Completed', timestamp: '20 Apr, 12:48 PM' },
  ];
  return steps.map((s, i) => ({
    ...s,
    status: i < current ? 'completed' : i === current ? 'active' : 'pending',
    timestamp: i <= current ? s.timestamp : undefined,
  }));
};

export const mockPro: ProUser = {
  id: 'pro_001',
  name: 'Arjun Mehta',
  phone: '+91 98765 43210',
  email: 'arjun.mehta@gmail.com',
  avatar: null,
  status: 'approved',
  isAvailable: true,
  zones: ['Surat South', 'Adajan', 'Vesu'],
  skills: ['AC Repair', 'Washing Machine', 'Refrigerator'],
  machineTypes: [
    'Split AC',
    'Window AC',
    'Front Load Washer',
    'Top Load Washer',
    'Single Door Fridge',
  ],
  serviceTypes: ['Diagnostic', 'Repair', 'Installation', 'Annual Service'],
  rating: 4.7,
  totalJobs: 84,
  bankDetails: {
    accountHolder: 'Arjun Mehta',
    accountNumber: '••••••••1234',
    ifsc: 'SBIN0001234',
    bankName: 'State Bank of India',
  },
};

export const mockJobs: Job[] = [
  {
    id: 'JOB-2847',
    status: 'new',
    serviceType: 'AC Repair',
    machineType: 'Split AC (1.5 Ton)',
    slot: 'Tomorrow, 10:00 AM – 12:00 PM',
    date: '21 Apr 2026',
    zone: 'Adajan, Surat',
    customerName: 'Customer #4821',
    address: null,
    parts: [],
    timeline: baseTimeline(0),
    earning: null,
  },
  {
    id: 'JOB-2841',
    status: 'inProgress',
    serviceType: 'Washing Machine Repair',
    machineType: 'Front Load Washer',
    slot: 'Today, 2:00 PM – 4:00 PM',
    date: '20 Apr 2026',
    zone: 'Vesu, Surat',
    customerName: 'Priya Sharma',
    address: '12, Shree Nagar Society, Vesu, Surat – 395007',
    diagnosis: ['Drum Issue', 'Drainage Issue'],
    parts: [
      { partId: 'p1', name: 'Drum Belt', variant: 'Universal Fit', qty: 1, status: 'available' },
      { partId: 'p2', name: 'Drain Pump', variant: '220V AC', qty: 1, status: 'outOfStock' },
    ],
    timeline: baseTimeline(3),
    earning: null,
  },
  {
    id: 'JOB-2838',
    status: 'accepted',
    serviceType: 'Refrigerator Repair',
    machineType: 'Single Door Fridge',
    slot: 'Today, 5:00 PM – 7:00 PM',
    date: '20 Apr 2026',
    zone: 'Surat South',
    customerName: 'Rahul Patel',
    address: '4B, Lake View Apartments, Adajan, Surat – 395009',
    parts: [],
    timeline: baseTimeline(1),
    earning: null,
  },
  {
    id: 'JOB-2832',
    status: 'readyResume',
    serviceType: 'AC Repair',
    machineType: 'Split AC (1.5 Ton)',
    slot: 'Tomorrow, 11:00 AM – 1:00 PM',
    date: '21 Apr 2026',
    zone: 'Vesu',
    customerName: 'Sneha Desai',
    address: '8, Lotus Avenue, Vesu, Surat',
    diagnosis: ['Compressor Failure', 'Gas Leak'],
    parts: [
      { partId: 'p3', name: 'Compressor', variant: '1.5 Ton', qty: 1, status: 'locked' },
      { partId: 'p4', name: 'Refrigerant Gas', variant: 'R32', qty: 1, status: 'locked' },
    ],
    timeline: baseTimeline(5),
    earning: null,
  },
  {
    id: 'JOB-2835',
    status: 'completed',
    serviceType: 'AC Repair',
    machineType: 'Split AC',
    slot: '18 Apr, 11:00 AM',
    date: '18 Apr 2026',
    zone: 'Adajan',
    customerName: 'Meera Joshi',
    address: '22, Krishna Society, Adajan, Surat',
    diagnosis: ['Gas Leak'],
    parts: [{ partId: 'p4', name: 'Refrigerant Gas', variant: 'R32', qty: 1, status: 'locked' }],
    timeline: baseTimeline(7),
    earning: 1020,
    rating: 5,
    ratingComment: 'Excellent work! Fixed AC very quickly and cleanly.',
  },
  {
    id: 'JOB-2829',
    status: 'rejected',
    serviceType: 'Geyser Repair',
    machineType: 'Storage Geyser',
    slot: '15 Apr, 4:00 PM',
    date: '15 Apr 2026',
    zone: 'Surat South',
    customerName: 'Customer #4801',
    address: null,
    parts: [],
    timeline: baseTimeline(0),
    earning: null,
  },
];

export const mockEarnings: Earning[] = [
  {
    id: 'e1',
    jobId: 'JOB-2835',
    serviceType: 'AC Repair',
    machineType: 'Split AC',
    date: '18 Apr 2026',
    grossEarning: 1200,
    commissionPct: 15,
    commissionAmount: 180,
    netEarning: 1020,
    status: 'paid',
    paidOn: '20 Apr 2026',
  },
  {
    id: 'e2',
    jobId: 'JOB-2829',
    serviceType: 'Refrigerator Repair',
    machineType: 'Single Door Fridge',
    date: '15 Apr 2026',
    grossEarning: 850,
    commissionPct: 15,
    commissionAmount: 128,
    netEarning: 722,
    status: 'pending',
  },
  {
    id: 'e3',
    jobId: 'JOB-2821',
    serviceType: 'Washing Machine',
    machineType: 'Top Load Washer',
    date: '10 Apr 2026',
    grossEarning: 650,
    commissionPct: 15,
    commissionAmount: 98,
    netEarning: 552,
    status: 'failed',
    failReason: 'Invalid IFSC code',
  },
  {
    id: 'e4',
    jobId: 'JOB-2815',
    serviceType: 'AC Service',
    machineType: 'Split AC',
    date: '5 Apr 2026',
    grossEarning: 900,
    commissionPct: 15,
    commissionAmount: 135,
    netEarning: 765,
    status: 'approved',
  },
];

export const mockProducts: Part[] = [
  { id: 'p1', name: 'Drum Belt', variant: 'Universal Fit', category: 'Belts', available: true },
  { id: 'p2', name: 'Drain Pump', variant: '220V AC', category: 'Cooling', available: false },
  { id: 'p3', name: 'Compressor', variant: '1.5 Ton', category: 'Cooling', available: true },
  { id: 'p4', name: 'Refrigerant Gas', variant: 'R32', category: 'Cooling', available: true },
  { id: 'p5', name: 'Capacitor', variant: '35/5 MFD', category: 'Electrical', available: true },
  { id: 'p6', name: 'Thermostat', variant: 'Digital', category: 'Electrical', available: false },
  { id: 'p7', name: 'PCB Board', variant: 'Universal', category: 'Electrical', available: true },
  { id: 'p8', name: 'Heating Element', variant: '2KW', category: 'Filters', available: true },
  { id: 'p9', name: 'Brake Pad', variant: 'Heavy Duty', category: 'Brakes', available: true },
  { id: 'p10', name: 'Engine Oil', variant: '5W-30 1L', category: 'Engine', available: true },
];

export const mockNotifications: AppNotification[] = [
  {
    id: 'n1',
    type: 'job',
    title: 'New Job Assigned',
    message: 'AC Repair job in Adajan for tomorrow 10 AM',
    time: '2m ago',
    read: false,
  },
  {
    id: 'n2',
    type: 'payment',
    title: 'Payout Processed',
    message: '₹1,020 transferred to your bank account',
    time: '1h ago',
    read: false,
  },
  {
    id: 'n3',
    type: 'job',
    title: 'Customer Approved Parts List',
    message: 'Priya Sharma approved the parts for JOB-2841',
    time: '3h ago',
    read: true,
  },
  {
    id: 'n4',
    type: 'failure',
    title: 'Payout Failed',
    message: '₹552 payout failed — invalid IFSC. Tap to fix.',
    time: 'Yesterday',
    read: false,
  },
  {
    id: 'n5',
    type: 'alert',
    title: 'Admin Message',
    message: 'New compliance training available in your dashboard.',
    time: '2 days ago',
    read: true,
  },
];

export const mockRatings: Rating[] = [
  {
    jobId: 'JOB-2835',
    stars: 5,
    comment: 'Excellent work! Fixed AC very quickly and cleanly.',
    serviceType: 'AC Repair',
    machineType: 'Split AC',
    date: '19 Apr 2026',
  },
  {
    jobId: 'JOB-2810',
    stars: 4,
    comment: 'Good service, was on time.',
    serviceType: 'Refrigerator Repair',
    machineType: 'Single Door Fridge',
    date: '5 Apr 2026',
  },
  {
    jobId: 'JOB-2802',
    stars: 5,
    comment: 'Very professional and explained everything clearly.',
    serviceType: 'Washing Machine',
    machineType: 'Front Load Washer',
    date: '28 Mar 2026',
  },
];

export const ALL_SKILLS = [
  'AC Repair',
  'Washing Machine',
  'Refrigerator',
  'Geyser',
  'Generator',
  'Electrical',
  'Plumbing',
];

export const ALL_ZONES = [
  'Surat South',
  'Adajan',
  'Vesu',
  'Athwa',
  'Citylight',
  'Piplod',
  'Rander',
];

export const ISSUE_TAGS = [
  'Compressor Failure',
  'Gas Leak',
  'Motor Issue',
  'PCB Fault',
  'Sensor Error',
  'Water Leakage',
  'Electrical Short',
  'Drum Issue',
  'Heating Element',
  'Thermostat Fault',
  'Belt Broken',
  'Drainage Issue',
  'Noise/Vibration',
  'Not Cooling',
  'Not Heating',
];

export const REJECT_REASONS = [
  'Too far from zone',
  'Already at capacity',
  'Skill mismatch',
  'Personal emergency',
  'Other',
];

export const UNAVAILABILITY_REASONS = [
  'On Leave',
  'Personal Emergency',
  'At Capacity',
  'End of Day',
  'Other',
];

export const PART_CATEGORIES = [
  'All',
  'Engine',
  'Filters',
  'Brakes',
  'Electrical',
  'Cooling',
  'Belts',
];
